### ISSUE TITLE
non uniprot fasta support

### ISSUE THREAD

**Issue by Owen-Duncan** [prvst/philosopher#7]
Could we have support for custom fasta files which don't meet the uniprot header format? Support for simple header structures such as that below would be appreciated as uniprot is often quite out of date. 

>customidentifier1
AMINOACIDSEQUENCE1
>customidentifier2
AMINOACIDSEQUENCE2

Regards, 

Owen

EDIT: simple naming structures do seem to be supported, fasta files just appear to need to  be named *.fas rather than *.fa or *.fasta

**Comment by prvst** [comment]
hey @Owen-Duncan ;

Teaching a tool to read custom formatted FASTA files can be very tricky. Philosopher uses the information on the headers to fill up some column on the protein report. We strongly suggest you to format your data base using the same pattern the UniProt or the NCBI groups does because then, Philosopher knows where to find a gene name or the organism name (notice that you don't need to download it from those online databases, just you their formatting style). So far, the latest version is compatible with simple headers like you pasted above, but because the tool can tell you what is what from the header, some columns on the report will be empty.

About the file extension, Philosopher should be able to read files with those extensions too, if its not, then you might have found a small bug, I'll take a look to see how to fix that.

Thanks

**Comment by Owen-Duncan** [comment]
Thanks Felipe, very much appreciate your time and effort.
